# Generated by Django 5.2.6 on 2025-09-13 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='concepto',
        ),
        migrations.AddField(
            model_name='deuda',
            name='concepto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='finanzas.conceptopago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptopago',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='anio_correspondiente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='mes_correspondiente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='medio_de_pago',
            field=models.CharField(default='Efectivo', max_length=50),
        ),
    ]
