# Generated by Django 5.2.6 on 2025-09-12 23:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='horarios',
        ),
        migrations.AddField(
            model_name='curso',
            name='dia_cursado',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], default=1),
        ),
        migrations.AddField(
            model_name='curso',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='modalidad_cursado',
            field=models.CharField(choices=[('Anual', 'Anual'), ('1C', '1er Cuatrimestre'), ('2C', '2do Cuatrimestre')], default='1C', max_length=5),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cuatrimestre',
            field=models.IntegerField(choices=[(0, 'Anual'), (1, '1er Cuatrimestre'), (2, '2do Cuatrimestre')], default=1),
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='academico.docente'),
        ),
    ]
