# Generated by Django 5.2.6 on 2025-09-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_remove_curso_horarios_curso_dia_cursado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='duracion_anios',
            field=models.IntegerField(choices=[(1, '1 Año'), (2, '2 Años'), (3, '3 Años'), (4, '4 Años'), (5, '5 Años')], default=3),
        ),
    ]
