# Generated by Django 5.2.6 on 2025-11-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_docente_user'),
        ('core', '0002_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='core.docente'),
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
