# Generated by Django 5.2.6 on 2025-11-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_curso_docente_delete_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vigencia', models.DateField(help_text='Fecha a partir de la cual este valor de cuota es válido.')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_historicos', to='academico.carrera')),
            ],
            options={
                'ordering': ['-fecha_vigencia'],
                'unique_together': {('carrera', 'fecha_vigencia')},
            },
        ),
    ]
