# Generated by Django 5.2.6 on 2025-11-03 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_docente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='docente',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL),
        ),
    ]
