# Generated by Django 5.2.6 on 2025-11-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_docente_apellido_remove_docente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=128)),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_perfil', models.CharField(choices=[('ADMIN', 'Administrativo'), ('DOCENTE', 'Docente')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
